export default {
  EOF: 'EOF',
  MNEMONIC: {
    DEST: {
      NONE: '',
      M: 'M',
      D: 'D',
      MD: 'MD',
      A: 'A',
      AM: 'AM',
      AD: 'AD',
      AMD: 'AMD',
    },
    JUMP: {
      NONE: '',
      JGT: 'JGT',
      JEQ: 'JEQ',
      JGE: 'JGE',
      JLT: 'JLT',
      JNE: 'JNE',
      JLE: 'JLE',
      JMP: 'JMP',
    },
    COMP: {
      $0: '0',
      $p1: '1',
      $m1: '-1',
      $D: 'D',
      $A: 'A',
      $nD: '!D',
      $nA: '!A',
      $mD: '-D',
      $mA: '-A',
      $Dp1: 'D+1',
      $Ap1: 'A+1',
      $Dm1: 'D-1',
      $Am1: 'A-1',
      $DpA: 'D+A',
      $DmA: 'D-A',
      $AmD: 'A-D',
      $DandA: 'D&A',
      $DorA: 'D|A',
      M: 'M',
      nM: '!M',
      mM: '-M',
      Mp1: 'M+1',
      Mm1: 'M-1',
      DpM: 'D+M',
      DmM: 'D-M',
      MmD: 'M-D',
      DandM: 'D&M',
      DorM: 'D|M',
    },
  },
}
